### ISSUE TITLE
Hacer tablero de visión del producto

### ISSUE THREAD

**Issue by JuanManuel-GAA** [JuanManuel-GAA/equipo7_gaa_ppi2020#2]

**Comment by marthaduque** [comment]
Falta adicionar la visión en el tablero y el tablero de visión se debe orientar al alcance aprobado que fue: Aplicativo movil que permite conocer la oferta de parques publicos y privados en el valle de aburra , el aplicativo permite conocer diferentes rutas para desplazarse a ellos y adicionalmente permite dar un puntaje dal sitio visitado.
